#!/usr/bin/env bash
# Bash script that will display information about subdomains

nosub () {
	digg="dig $2.$1"
	sub=$($digg | grep -A1 'ANSWER SECTION:' | cut -d '.' -f1 | tail -1)
	record=$($digg | grep -A1 'ANSWER SECTION:' | cut -d $'\t' -f4 | tail -1)
	dest=$($digg | grep -A1 'ANSWER SECTION:' | cut -d $'\t' -f5 | tail -1)
	echo "$sub $record $dest" | awk '{print "The subdomain", $1, "is a",$2, "record and points to", $3}'
}

if [ $# -eq 1 ];
then
{
	nosub "$1" "www"
	nosub "$1" "lb-01"
	nosub "$1" "web-01"
	nosub "$1" "web-02"
}
fi
if [[ $# -eq 2 ]]; 
then
{
	nosub "$1" "$2"
}
fi
