#!/usr/bin/env bash
# Configure an Nginx server so that /redirect_me is redirecting to another page

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location /redirect_me {
               return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
       }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
