#!/usr/bin/env bash
# Configure an Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

	error_page 404 /error.html;
	location = /error.html {
		root /var/www/html;
		internal;
	}	

        location /redirect_me {
               return 301 https://google.com;
       }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
