#!/usr/bin/env bash
# A script to install and configure HAproxy on a server

sudo apt update
sudo apt install -y software-properties-common
sudo apt install -y haproxy

append="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 10634-web-01	54.208.96.82:80 check
    server 10634-web-02	35.153.192.97:80 check
"
echo "$append" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
