#!/usr/bin/env bash
#Bash script that to automate a fix to what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pkill -1 nginx
