#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

hour=0

while [ $hour -ne 13 ]
do
	minutes=1
	echo "Hour: $hour"
	while [ $minutes -ne 60 ]
	do
		echo "$minutes"
		minutes=$((minutes + 1))
	done
	hour=$((hour + 1))
done
