#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server:
# localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/newhosts
echo -e "127.0.0.2\tlocalhost" > ~/newhosts
echo -e "8.8.8.8\tfacebook.com" >> ~/newhosts
cp -f ~/newhosts /etc/hosts
