#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server:
# localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2       localhost" > ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
